### ISSUE TITLE
Deployments while keeping network isolation

### ISSUE THREAD

**Issue by gavanderhoorn** [ct2034/dockeROS#1]
From [this line](https://github.com/ct2034/dockeROS/blob/98a68308da794422c3e45cb5586924681d43661b/src/dockeros/image.py#L203) it seems that the network isolation of Docker is not used / disabled and instead binding of sockets is done against the `host`'s  network stack.

Do you have any experience with automating deployments/starting nodes with `dockeROS` while keeping network isolation enabled?

**Comment by ct2034** [comment]
Thanks for the comment. The problem is that ros randomly assigns ports to the started node. But to open a port in docker, you would need to expose the port when starting the container (but you don't know it, because it will only later be randomly assigned). So the host network is currently the only way.

I was thinking about having a predefined port to the outside and some reverse proxy inside the container. But I don't know what the overhead of that would be.

**Comment by ct2034** [comment]
Congrats on the first issue, btw :+1:

**Comment by gavanderhoorn** [comment]
> Thanks for the comment. The problem is that ros randomly assigns ports to the started node. But to open a port in docker, you would need to expose the port when starting the container (but you don't know it, because it will only later be randomly assigned). So the host network is currently the only way.
> 
> I was thinking about having a predefined port to the outside and some reverse proxy inside the container. But I don't know what the overhead of that would be.

Have you thought about using a virtual subnet with routable IPs? You can configure Docker to use that instead of the default NAT network. Every node (well .. container) would then get its own IP, which circumvents the "random port" issue.

It also makes it easier to have Docker containers communicate with off-host nodes (as long as there is a route to the virtual subnet).

> Congrats on the first issue, btw +1

Well I wanted to ask this as a question after your presentation but somehow got skipped :)

**Comment by gavanderhoorn** [comment]
As this was more of a question and not so much an issue I'll close this.

Thanks for the tool, much appreciated :+1:
